map_type: costmap

obstacle_range: 1.0 # 2.0
raytrace_range: 2.0 # 3.0

# transform_tolerance: 0.2 # 0.0
# JF:
transform_tolerance: 0.4 # 0.0

robot_radius: 0.3 # 0.0
inflation_radius: 1.2 # JF: large inflation for path-planner safety for skid-steer robot # 0.5
cost_scaling_factor: 5.0

# Per the q802_skid_steer_bot.xacro *_wheel_hinge xy offsets
footprint: 
  - [0.225, 0.2]
  - [0.225, -0.2]
  - [-0.225, -0.2]
  - [-0.225, 0.2]
footprint_padding: 0.25 # 0.05

observation_sources: laser_scan_sensor

# laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
